apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1  # ✅ Added replicas for clarity
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: docker.io/mongo
          ports:
            - containerPort: 27017
          env:  # ✅ Corrected indentation
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
